import React from 'react';
import Navbar from '../components/Navbar';
import GlassCard from '../components/GlassCard';
import { Sparkles, FileText, Send, Save, BookOpen } from 'lucide-react';
import './OracleWriter.css';

const OracleWriter = () => {
  return (
    <div className="page-container">
      <Navbar title="Oracle Writer" />
      
      <div className="page-content writer-layout animate-fade-in">
        
        {/* Left Side: Requirements & DNA context */}
        <div className="writer-context">
          <GlassCard className="context-panel h-full flex-col">
            <div className="panel-header">
              <div className="flex items-center gap-2">
                <BookOpen className="text-gold" size={20} />
                <h4 className="font-display">Grant Parameters</h4>
              </div>
            </div>
            
            <div className="context-body">
              <div className="context-section">
                <h5 className="text-muted text-uppercase">Target Funder</h5>
                <p className="text-primary font-display">Lumina Foundation Catalyst Fund</p>
              </div>
              
              <div className="context-section">
                <h5 className="text-muted text-uppercase">Prompt</h5>
                <p className="text-secondary text-sm">
                  "Describe how your organization plans to leverage technology to enhance educational outcomes for underrepresented youth in the next 24 months."
                </p>
              </div>

              <div className="context-section">
                <h5 className="text-muted text-uppercase">Data Vault Injections</h5>
                <ul className="vault-list">
                  <li><CheckIcon /> 2025 Impact Report (Youth Demographics)</li>
                  <li><CheckIcon /> Board Member Biographies</li>
                  <li><CheckIcon /> Q3 Financial Audit</li>
                </ul>
              </div>
            </div>

            <div className="context-footer mt-auto">
              <button className="btn btn-outline w-full">
                <Sparkles size={16} />
                <span>Regenerate Draft</span>
              </button>
            </div>
          </GlassCard>
        </div>

        {/* Right Side: The Editor */}
        <div className="writer-editor">
          <GlassCard className="editor-panel h-full flex-col">
            <div className="editor-toolbar">
              <div className="flex gap-4">
                <button className="toolbar-btn">Format</button>
                <button className="toolbar-btn">Tone: Persuasive</button>
                <button className="toolbar-btn">Length: ~500 words</button>
              </div>
              <div className="flex gap-2">
                <button className="btn btn-ghost"><Save size={18} /></button>
                <button className="btn btn-primary"><Send size={18} /> Audit & Grade</button>
              </div>
            </div>
            
            <div className="editor-workspace">
              <textarea 
                className="ai-textarea"
                defaultValue={`Our organization stands at the vanguard of educational equity, recognizing that access to technology is not merely a convenience, but a fundamental right in the 21st century.

Drawing upon our successful 2025 Impact Report, which demonstrated a 40% increase in digital literacy among our target demographic, we are positioned to scale our "Tech-Forward Youth" initiative.

The Lumina Foundation Catalyst Fund will enable us to deploy 500 new interactive learning terminals to underserved districts. By integrating AI-driven personalized tutoring software, we project a minimum 25% improvement in standardized test scores over the next 24 months. 

Our board, comprising leading technologists and educators, guarantees the rigorous oversight and innovative execution required to transform this vision into measurable reality.`}
              />
            </div>
            <div className="editor-footer">
              <span className="text-muted text-sm">Draft generated by Oracle AI • 124 words</span>
            </div>
          </GlassCard>
        </div>

      </div>
    </div>
  );
};

const CheckIcon = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="var(--color-accent-emerald)" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
    <polyline points="20 6 9 17 4 12"></polyline>
  </svg>
);

export default OracleWriter;
